#!/usr/bin/env python3

from analyzer import Analyzer
from termcolor import colored

import sys
import os
import cs50
import helpers


if len(sys.argv) != 2:
    sys.exit("Usage: ./tweets twitter_account")

screen_name = sys.argv[1]
tweets = helpers.get_user_timeline(screen_name, 50)
positives = os.path.join(sys.path[0], "positive-words.txt")
negatives = os.path.join(sys.path[0], "negative-words.txt")

# instantiate analyzer
analyzer = Analyzer(positives, negatives)
    
for tweet in tweets:
    score = analyzer.analyze(tweet)
    result = str(score) + " " + tweet
    if score > 0:
        print(colored(result, "green"))
    elif score < 0:
        print(colored(result, "red"))
    else:
        print(colored(result, "yellow"))